In [6]:
import pandas as pd

# Read the comma-separated CSV properly
messages = pd.read_csv('spam.csv', encoding='latin-1')

# Rename relevant columns if needed
messages = messages.rename(columns={
    messages.columns[0]: "label",
    messages.columns[1]: "message"
})

# Drop unnecessary columns if they exist (depends on your CSV)
messages = messages[["label", "message"]]

# Check the result
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
#Data cleaninig and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Anya
[nltk_data]     Anu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [9]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [10]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

### Create Bag of Words

In [17]:
#Create Bag of Words
from sklearn.feature_extraction.text import CountVectorizer
#for Binary enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [18]:
X=cv.fit_transform(corpus).toarray()

In [19]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [20]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [21]:
cv.vocabulary_

{'go': 801,
 'point': 1605,
 'crazi': 452,
 'avail': 123,
 'bugi': 230,
 'great': 855,
 'world': 2430,
 'la': 1084,
 'cine': 349,
 'got': 843,
 'wat': 2338,
 'ok': 1472,
 'lar': 1096,
 'joke': 1051,
 'wif': 2395,
 'free': 723,
 'entri': 617,
 'wkli': 2419,
 'comp': 400,
 'win': 2400,
 'fa': 653,
 'cup': 466,
 'final': 688,
 'st': 1961,
 'may': 1265,
 'text': 2074,
 'receiv': 1699,
 'question': 1664,
 'std': 1976,
 'txt': 2203,
 'rate': 1679,
 'appli': 86,
 'free entri': 728,
 'entri wkli': 619,
 'std txt': 1977,
 'txt rate': 2209,
 'rate appli': 1680,
 'dun': 577,
 'say': 1795,
 'earli': 583,
 'alreadi': 55,
 'nah': 1386,
 'think': 2100,
 'goe': 823,
 'usf': 2273,
 'live': 1163,
 'around': 99,
 'though': 2110,
 'freemsg': 735,
 'hey': 921,
 'darl': 483,
 'week': 2363,
 'word': 2425,
 'back': 140,
 'like': 1148,
 'fun': 755,
 'still': 1979,
 'tb': 2052,
 'xxx': 2465,
 'send': 1826,
 'even': 627,
 'brother': 220,
 'speak': 1942,
 'treat': 2178,
 'per': 1543,
 'request': 1733,
 'mell': 12

In [22]:
##Output Feature
y=pd.get_dummies(messages['label'])

In [23]:
y

ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [24]:
y=y.iloc[:,0].values

In [25]:
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [29]:
y_pred=spam_detect_model.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test,y_pred)

0.9820627802690582

In [32]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.95      0.91      0.93       150
        True       0.99      0.99      0.99       965

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



### Creating The TFIDF Model

In [47]:
import pandas as pd

# Read your dataset
df = pd.read_csv("spam.csv", encoding='ISO-8859-1')

# Suppose the message column is named 'v2' (as in many spam datasets)
X = df['v2']  # Raw text messages
y = df['v1']  # Labels (spam/ham)

# Now split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [48]:
## Create tf-idf features
from sklearn.feature_extraction.text import TfidfVectorizer

# Assume X_train and X_test are pandas Series of text data
tv = TfidfVectorizer(max_features=2500, ngram_range=(1, 2))

X_train_tfidf = tv.fit_transform(X_train).toarray()
X_test_tfidf = tv.transform(X_test).toarray()


In [49]:
X_train

1978    No I'm in the same boat. Still here at my moms...
3989    (Bank of Granite issues Strong-Buy) EXPLOSIVE ...
3935       They r giving a second chance to rahul dengra.
4078       O i played smash bros  &lt;#&gt;  religiously.
4086    PRIVATE! Your 2003 Account Statement for 07973...
                              ...                        
3772    I came hostel. I m going to sleep. Plz call me...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860                   In work now. Going have in few min.
Name: v2, Length: 4457, dtype: object

In [50]:
tv.vocabulary_

{'no': 1405,
 'in': 963,
 'the': 1943,
 'same': 1701,
 'still': 1849,
 'here': 881,
 'at': 210,
 'my': 1350,
 'check': 401,
 'me': 1243,
 'out': 1528,
 'on': 1475,
 'yo': 2407,
 'half': 835,
 'in the': 982,
 'the same': 1967,
 'at my': 215,
 'bank': 246,
 'of': 1446,
 'strong': 1859,
 'buy': 319,
 'pick': 1562,
 'for': 682,
 'our': 1524,
 'up': 2162,
 'over': 1533,
 'that': 1928,
 'is': 1004,
 '00': 0,
 'per': 1549,
 'that is': 1932,
 'they': 1988,
 'second': 1716,
 'chance': 389,
 'to': 2035,
 'chance to': 390,
 'lt': 1204,
 'gt': 809,
 'lt gt': 1206,
 'private': 1611,
 'your': 2476,
 '2003': 48,
 'account': 100,
 'statement': 1844,
 'shows': 1767,
 '800': 79,
 'un': 2152,
 'redeemed': 1656,
 'points': 1593,
 'call': 326,
 'identifier': 944,
 'code': 423,
 'expires': 642,
 '10': 19,
 '04': 7,
 'private your': 1612,
 'your 2003': 2477,
 '2003 account': 49,
 'account statement': 101,
 'statement for': 1845,
 'shows 800': 1768,
 '800 un': 80,
 'un redeemed': 2153,
 'redeemed points': 165

In [53]:
#train test split
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)
y_pred = spam_tfidf_model.predict(X_test)

ValueError: could not convert string to float: "No I'm in the same boat. Still here at my moms. Check me out on yo. I'm half naked."

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

# Step 1: Load data
import pandas as pd
df = pd.read_csv("spam.csv", encoding='ISO-8859-1')
X = df['v2']   # messages
y = df['v1']   # labels (spam/ham)

# Step 2: Split data
X_train_raw, X_test_raw, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: TF-IDF transform
tv = TfidfVectorizer(max_features=2500, ngram_range=(1, 2))
X_train = tv.fit_transform(X_train_raw).toarray()
X_test = tv.transform(X_test_raw).toarray()

# Step 4: Train Naive Bayes
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)
y_pred = spam_tfidf_model.predict(X_test)

# Step 5: Evaluate
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

         ham       0.97      1.00      0.99       965
        spam       1.00      0.82      0.90       150

    accuracy                           0.98      1115
   macro avg       0.99      0.91      0.94      1115
weighted avg       0.98      0.98      0.97      1115



In [36]:
score=accuracy_score(y_test,y_pred)
print("Accuracy of the model is: ", score)

Accuracy of the model is:  0.9775784753363229


In [39]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       1.00      0.83      0.91       150
        True       0.97      1.00      0.99       965

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

